name: Lambda Invoke and ASG Check

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  invoke_and_check:
    name: Invoke Lambda and Check ASG
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::641002720432:role/ec2-role
        aws-region: us-east-1
        
    - name: Make script executable
      run: chmod +x lambda_invoke_with_github_actions.sh
        
    - name: Run Lambda Invoke and ASG Check
      run: ./lambda_invoke_with_github_actions.sh
